Repository 2ndsprout/2nd_project, pull requests merged in 2024-08, with the labels that each got.

#262 서비스 요청페이지 및 비밀글 보기 기능
  backend/src/main/java/com/second_team/apt_project/controllers/ProposeController.java
  backend/src/main/java/com/second_team/apt_project/services/module/ProposeService.java
  frontend/src/app/API/NonUserAPI.tsx
  frontend/src/app/account/profile/page.tsx
  frontend/src/app/propose/create/page.tsx
  frontend/src/app/propose/page.tsx
Labels: 수정, 개발, 백엔드, 프론트엔드

#274 MainLayout 파일명 깃에서 수정
  frontend/src/app/Global/layout/MainLayout.tsx
Labels: 수정, 프론트엔드

#280 logo add and group register fix and qsdquery update
  backend/src/main/java/com/second_team/apt_project/controllers/ProfileController.java
  backend/src/main/java/com/second_team/apt_project/domains/Profile.java
  backend/src/main/java/com/second_team/apt_project/repositories/customs/impls/UserRepositoryImpl.java
  backend/src/main/java/com/second_team/apt_project/services/MultiService.java
  backend/src/main/java/com/second_team/apt_project/services/module/EmailService.java
  frontend/public/logo.png
  frontend/src/app/Global/layout/AdminLayout.tsx
  frontend/src/app/Global/layout/MainLayout.tsx
  frontend/src/app/account/login/page.tsx
  frontend/src/app/account/profile/page.tsx
  frontend/src/app/propose/page.tsx
Labels: 수정, 백엔드, 프론트엔드

#284 layout fix
  backend/src/main/java/com/second_team/apt_project/services/module/EmailService.java
  frontend/src/app/Global/layout/AdminLayout.tsx
  frontend/src/app/Global/layout/MainLayout.tsx
  frontend/src/app/Global/layout/SideList.tsx
  frontend/src/app/account/admin/page.tsx
  frontend/src/app/propose/page.tsx
Labels: 수정, 프론트엔드

#297 Lee
  backend/src/main/java/com/second_team/apt_project/configs/WebConfig.java
  backend/src/main/java/com/second_team/apt_project/configs/WebSocketConfig.java
  backend/src/main/java/com/second_team/apt_project/enums/OsType.java
  backend/src/main/resources/application.yml
  frontend/.idea/workspace.xml
  frontend/next.config.mjs
  frontend/src/app/API/AxiosAPI.tsx
  frontend/src/app/account/FAQ/page.tsx
  frontend/src/app/account/admin/category/page.tsx
  frontend/src/app/account/admin/page.tsx
  frontend/src/app/account/admin/user/page.tsx
  frontend/src/app/account/article/[categoryId]/create/page.tsx
  frontend/src/app/account/article/[categoryId]/detail/[articleId]/page.tsx
  frontend/src/app/account/article/[categoryId]/page.tsx
  frontend/src/app/account/article/[categoryId]/update/[articleId]/page.tsx
  frontend/src/app/account/article/comment/CommentList.tsx
  frontend/src/app/account/article/love/LoveButton.tsx
  frontend/src/app/account/article/tag/TagInput.tsx
  frontend/src/app/account/culture_center/page.tsx
  frontend/src/app/account/mypage/lesson/[id]/modify/page.tsx
  frontend/src/app/account/mypage/lesson/create/page.tsx
  frontend/src/app/account/mypage/lesson/list/page.tsx
  frontend/src/app/account/mypage/lesson/manage/page.tsx
  frontend/src/app/account/mypage/page.tsx
  frontend/src/app/account/profile/page.tsx
  frontend/src/app/page.tsx
Labels: 수정, 개발, 백엔드, 프론트엔드

#307 center page fix
  frontend/src/app/account/culture_center/[id]/page.tsx
Labels: 수정, 개발, 프론트엔드

#315 Jun
  frontend/public/slider_default.png
  frontend/src/app/Global/component/Slider.tsx
  frontend/src/app/account/culture_center/[id]/page.tsx
  frontend/src/app/account/culture_center/page.tsx
  frontend/src/app/account/mypage/culture_center/page.tsx
  frontend/src/app/page.tsx
  run-backend.bat
Labels: 수정, 개발, 프론트엔드

#319 Jun
  frontend/src/app/account/mypage/culture_center/page.tsx
Labels: 수정, 개발, 프론트엔드

#327 Lee
  backend/src/main/java/com/second_team/apt_project/services/MultiService.java
  frontend/src/app/API/UserAPI.tsx
  frontend/src/app/Global/layout/MainLayout.tsx
  frontend/src/app/account/FAQ/page.tsx
  frontend/src/app/account/article/[categoryId]/create/page.tsx
  frontend/src/app/account/article/[categoryId]/detail/[articleId]/page.tsx
  frontend/src/app/account/article/[categoryId]/page.tsx
  frontend/src/app/account/article/[categoryId]/update/[articleId]/page.tsx
  frontend/src/app/account/culture_center/[id]/page.tsx
  frontend/src/app/account/culture_center/page.tsx
  frontend/src/app/account/lesson/[id]/page.tsx
  frontend/src/app/account/mypage/page.tsx
  run-backend.bat
Labels: 수정, 백엔드, 프론트엔드

#328 final fix
  backend/src/main/java/com/second_team/apt_project/configs/WebConfig.java
  frontend/next.config.mjs
  frontend/src/app/API/AxiosAPI.tsx
  frontend/src/app/Global/layout/MainLayout.tsx
  frontend/src/app/account/FAQ/page.tsx
  frontend/src/app/account/article/[categoryId]/page.tsx
  frontend/src/app/account/culture_center/[id]/page.tsx
  frontend/src/app/page.tsx
Labels: 수정, 프론트엔드
